name: "MSIX Build"
description: "An action automates the process of building an MSIX package."

inputs:
  app-build-path:
    description: "The path to the app build"
    required: true
  icon-path:
    description: "The path to the app icon"
    required: true
  appx-manifest-path:
    description: "The path to the AppxManifest.xml file"
    required: true
  priconfig-path:
    description: "The path to the priconfig.xml file"
    required: true

outputs:
  msix-path:
    description: "The path to the generated MSIX file"
    value: ${{ steps.msix_build_step.outputs.msix-path }}

runs:
  using: "composite"
  steps:
    - name: Set Environment Variables
      shell: pwsh
      run: |
        $workDir = Join-Path "${{ runner.temp }}" "msix-build"
        echo "WORKING_DIRECTORY=$workDir" >> $env:GITHUB_ENV

    - name: Setup ImageMagick
      shell: pwsh
      run: choco install imagemagick --no-progress

    - name: Add Windows SDK to PATH
      shell: pwsh
      run: |
        $kits = "C:\Program Files (x86)\Windows Kits\10\bin"
        # 1. 获取该目录下版本号最大的文件夹 (例如 10.0.22621.0)
        $latest = Get-ChildItem $kits | Where-Object { $_.PSIsContainer } | Sort-Object Name -Descending | Select-Object -First 1

        # 2. 拼接 x64 路径
        $sdkPath = Join-Path $latest.FullName "x64"

        # 3. 输出并添加到 GitHub PATH
        Write-Host "Detected latest Windows SDK: $sdkPath"
        echo "$sdkPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

    - name: Create Working Directory
      shell: pwsh
      run: |
        if (!(Test-Path "${{ env.WORKING_DIRECTORY }}")) {
          New-Item -ItemType Directory -Path "${{ env.WORKING_DIRECTORY }}" -Force
        }

    - name: Generate UWP Icons
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        chmod +x "${{ github.action_path }}/scripts/generate_uwp_icons.sh"
        "${{ github.action_path }}/scripts/generate_uwp_icons.sh" "${{ github.workspace }}/${{ inputs.icon-path }}"
        # outputs to ${{ env.WORKING_DIRECTORY }}/Assets

    - name: Copy input files
      shell: pwsh
      run: |
        # copy appx manifest to ${{ env.WORKING_DIRECTORY }}/AppxManifest.xml
        Copy-Item -Path "${{ github.workspace }}/${{ inputs.appx-manifest-path }}" -Destination ${{ env.WORKING_DIRECTORY }}/AppxManifest.xml -Force

        # copy all files under app build to ${{ env.WORKING_DIRECTORY }}/Source
        $sourceWithWildcard = Join-Path -Path "${{ github.workspace }}/${{ inputs.app-build-path }}" -ChildPath "*"
        $dest = Join-Path -Path $env:WORKING_DIRECTORY -ChildPath "Source"
        if (!(Test-Path -Path $dest)) {
          New-Item -ItemType Directory -Path $dest -Force | Out-Null
        }
        Copy-Item -Path $sourceWithWildcard -Destination $dest -Recurse -Force

    - name: Generate resources.pri
      working-directory: ${{ env.WORKING_DIRECTORY }}
      shell: pwsh
      run: |
        makepri new /pr . /cf "${{ github.workspace }}/${{ inputs.priconfig-path }}" /mn AppxManifest.xml /of /o
        # outputs to ${{ env.WORKING_DIRECTORY }}/resources.pri
    
    - name: Build MSIX
      id: msix_build_step
      working-directory: ${{ env.WORKING_DIRECTORY }}
      shell: pwsh
      run: |

        makeappx pack /d . /p ./out.msix /o
        # outputs to ${{ env.WORKING_DIRECTORY }}/out.msix

        $fullPath = Join-Path $env:WORKING_DIRECTORY "out.msix"
        "msix-path=$fullPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
